import numpy as np


class PController(object):
    '''
    Proportional supervisor controller
    '''

    def __init__(self, configuration):

        self.K = configuration.K
        self.action_mask = configuration.action_mask

        return

    def supervisor_action(self, x):
        '''
        Compute the input generated by the controller

        :param x: state
        :return: input vector
        '''

        u = - np.matmul(self.K, x)

        return u